import { test, expect } from './fixtures';

test('Markdown draft, language switching, autosave, safe preview, conflicts and home curation', async ({page,context})=>{
  await page.goto('/auth/login');
  await page.getByLabel('Email',{exact:true}).fill('admin@example.com');
  await page.getByLabel('Password',{exact:true}).fill('Admin-test-password-123');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('link',{name:'Administer',exact:true}).click();
  await page.locator('[name=title]').fill('Editorial course');
  await page.locator('[name=slug]').fill('editorial-course');
  await page.locator('[name=summary]').fill('A course prepared in the new author studio.');
  await page.locator('[name=accessMode]').selectOption('OPEN_FREE');
  await page.getByLabel('Learning objectives', {exact:true}).fill('Build a project <script>unsafe</script>');
  await page.getByLabel('Prerequisites', {exact:true}).fill('Basic programming');
  await page.locator('[name=level]').selectOption('beginner');
  await page.locator('[name=durationMinutes]').fill('90');
  await page.getByLabel('Instructor name', {exact:true}).fill('Course instructor');
  await page.getByLabel('Instructor biography', {exact:true}).fill('Teaches <b>programming</b>');
  await page.getByLabel('Access terms', {exact:true}).fill('Free access to these lessons');
  await page.getByLabel('Certificate information', {exact:true}).fill('No certificate included');
  await page.locator('.module-title').fill('Introduction');
  await page.locator('.lesson-title').fill('Markdown lesson');
  const markdown='# Hello\n\n**Strong text**\n\n<script>alert("unsafe")</script>';
  await page.locator('.lesson-content').fill(markdown);
  for(const language of ['pt-BR','es','en']) {
    await page.locator('#languageSelect').selectOption(language);
    await expect(page.locator('html')).toHaveAttribute('lang',language);
    await expect(page.locator('.lesson-content')).toHaveValue(markdown);
    await expect(page.locator('[name=title]')).toHaveValue('Editorial course');
    await expect(page.locator('[name=learningOutcomes]')).toHaveValue('Build a project <script>unsafe</script>');
    await expect(page.locator('[name=durationMinutes]')).toHaveValue('90');
    await expect(page.locator('[name=instructorName]')).toHaveValue('Course instructor');
    await expect(page.locator('[name=accessTerms]')).toHaveValue('Free access to these lessons');
  }
  await page.getByRole('button',{name:'Preview content',exact:true}).click();
  await expect(page.locator('.content-preview h1')).toHaveText('Hello');
  await expect(page.locator('.content-preview strong')).toHaveText('Strong text');
  await expect(page.locator('.content-preview script')).toHaveCount(0);
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  const card=page.locator('#admin-list .card').filter({has:page.getByRole('heading',{name:'Editorial course',exact:true})});
  await card.getByRole('button',{name:'Publish',exact:true}).click();
  await expect(card).toContainText('PUBLISHED');
  const list=await (await page.request.get('/api/v1/admin/courses')).json();
  const course=list.find(c=>c.slug==='editorial-course');
  const old=(await (await page.request.get(`/api/v1/courses/${course.id}`)).json()).modules[0].lessons[0].id;
  await page.locator('.lesson-content').fill('## A new draft\n\nOnly the author sees this.');
  await expect(page.locator('#save-status')).toContainText('Draft saved',{timeout:10000});
  expect((await (await page.request.get(`/api/v1/lessons/${old}`)).json()).body).toBe(markdown);
  const draft=await (await page.request.get(`/api/v1/admin/courses/${course.id}`)).json();
  expect(draft.modules[0].lessons[0].body).toContain('Only the author');
  await card.getByRole('button',{name:'Edit',exact:true}).click();
  await expect(page.locator('.lesson-content')).toHaveValue('## A new draft\n\nOnly the author sees this.');
  // A second editor saves first: local work must not overwrite it silently.
  const other=await context.newPage();await other.goto('/admin');
  await other.locator('#admin-list .card').filter({has:other.getByRole('heading',{name:'Editorial course',exact:true})}).getByRole('button',{name:'Edit',exact:true}).click();
  await page.locator('.lesson-content').fill('First editor wins');
  await expect(page.locator('#save-status')).toContainText('Draft saved',{timeout:10000});
  await other.locator('.lesson-content').fill('Keep this conflicting local text');
  await expect(other.locator('#save-status')).toContainText('Another editor changed',{timeout:10000});
  await expect(other.locator('.lesson-content')).toHaveValue('Keep this conflicting local text');
  other.on('dialog',dialog=>dialog.accept());await other.close();
  // Curate the public home. This leaves the published course content unchanged.
  await page.getByRole('link',{name:'Manage homepage',exact:true}).click();
  await page.getByRole('button',{name:'Add course placement'}).click();
  await page.locator('.placement-course').selectOption(course.id);
  await page.locator('.placement-slot').selectOption('featured');
  await page.getByRole('button',{name:'Save homepage'}).click();
  await expect(page.locator('#home-status')).toHaveText('Homepage saved.');
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Featured courses',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Editorial course',exact:true})).toBeVisible();
  await page.goto(`/courses/${course.id}`);
  await expect(page.locator('.course-presentation')).toContainText('Basic programming');
  await expect(page.locator('.course-presentation')).toContainText('Build a project <script>unsafe</script>');
  await expect(page.locator('.course-presentation')).toContainText('90');
  await expect(page.locator('.course-presentation')).toContainText('Course instructor');
  await expect(page.locator('.course-presentation')).toContainText('Teaches <b>programming</b>');
  await expect(page.locator('.course-presentation b')).toHaveCount(0);
  await expect(page.locator('.course-presentation')).toContainText('Free access to these lessons');
  await expect(page.locator('.course-presentation')).toContainText('Certificates are not currently issued');
  await expect(page.locator('.course-presentation script')).toHaveCount(0);
  await page.goto(`/lessons/${old}`);
  await expect(page.locator('.lesson-body h1')).toHaveText('Hello');
  await page.screenshot({path:'test-results/markdown-lesson.png',fullPage:true});
});

test('recovers a local draft after reload and reorders lessons with keyboard-accessible controls',async({page})=>{
  await page.goto('/auth/login');
  await page.getByLabel('Email',{exact:true}).fill('admin@example.com');
  await page.getByLabel('Password',{exact:true}).fill('Admin-test-password-123');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('link',{name:'Administer',exact:true}).click();
  await page.locator('[name=title]').fill('Recover this course');
  await page.locator('.lesson-content').fill('Local text not saved to the server');
  page.on('dialog',dialog=>dialog.accept());
  await page.reload();
  await expect(page.locator('[name=title]')).toHaveValue('Recover this course');
  await expect(page.locator('.lesson-content')).toHaveValue('Local text not saved to the server');
  await page.locator('.lesson-title').fill('First');
  await page.locator('.lesson-editor > .row-controls').getByRole('button',{name:'Duplicate',exact:true}).click();
  await page.locator('.lesson-title').nth(1).fill('Second');
  await page.locator('.lesson-editor').nth(1).locator(':scope > .row-controls').getByRole('button',{name:'Move up',exact:true}).click();
  await expect(page.locator('.lesson-title').first()).toHaveValue('Second');
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('#editor')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/studio-mobile.png',fullPage:true});
});

test('focused studio preserves content across navigation and language changes, and drag order survives save', async ({ page }) => {
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Admin-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('link', { name: 'Administer', exact: true }).click();
  await page.locator('[name=title]').fill('Focused course');
  await page.locator('[name=slug]').fill('focused-course');
  await page.locator('[name=summary]').fill('A course for focused editing and reordering.');
  await page.locator('.module-title').fill('Introduction');
  await page.locator('.lesson-title').fill('First lesson');
  await page.locator('.lesson-content').fill('First body');
  await page.locator('.lesson-editor > .row-controls').getByRole('button', { name: 'Duplicate', exact: true }).click();
  await page.locator('.lesson-title').nth(1).fill('Second lesson');
  await page.locator('.lesson-content').nth(1).fill('Second body');
  await page.getByLabel('Edit one section at a time', { exact: true }).check();
  const outline = page.locator('.studio-outline');
  await outline.getByRole('button', { name: '1.1. First lesson', exact: true }).click();
  await expect(page.locator('#course-settings')).toBeHidden();
  await expect(page.locator('.lesson-editor').nth(1)).toBeHidden();
  await page.locator('.lesson-content').first().fill('Edited while focused');
  await outline.getByRole('button', { name: '1.2. Second lesson', exact: true }).click();
  await expect(page.locator('.lesson-content').nth(1)).toHaveValue('Second body');
  for (const locale of ['pt-BR', 'es', 'en']) {
    await page.locator('#languageSelect').selectOption(locale);
    await expect(page.locator('.lesson-editor').first()).toBeHidden();
    await expect(page.locator('.lesson-editor').nth(1)).toBeVisible();
    await expect(page.locator('.lesson-content').first()).toHaveValue('Edited while focused');
  }
  // Invalid fields in hidden sections are revealed before native validation focuses them.
  await page.locator('.lesson-title').nth(1).fill('');
  await outline.getByRole('button', { name: 'Course settings', exact: true }).click();
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('.lesson-editor').nth(1)).toBeVisible();
  await page.locator('.lesson-title').nth(1).fill('Second lesson');
  await page.getByLabel('Edit one section at a time', { exact: true }).uncheck();
  const source = page.locator('.lesson-editor').nth(1).locator(':scope > .row-controls .drag-handle');
  const target = page.locator('.lesson-editor').first().locator(':scope > .row-controls .drag-handle');
  await source.hover();
  const bounds = await source.boundingBox();
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width / 2 + 12, bounds.y + bounds.height / 2, { steps: 5 });
  await target.hover();
  await target.hover();
  await page.mouse.up();
  await expect(page.locator('.lesson-title').first()).toHaveValue('Second lesson');
  await page.locator('.module-editor > .row-controls').getByRole('button', { name: 'Duplicate', exact: true }).click();
  await page.locator('.module-title').nth(1).fill('Advanced');
  const moduleSource = page.locator('.module-editor').nth(1).locator(':scope > .row-controls .drag-handle');
  const moduleTarget = page.locator('.module-editor').first().locator(':scope > .row-controls .drag-handle');
  await moduleSource.hover();
  const moduleBounds = await moduleSource.boundingBox();
  await page.mouse.down();
  await page.mouse.move(moduleBounds.x + moduleBounds.width / 2 + 12, moduleBounds.y + moduleBounds.height / 2, { steps: 5 });
  await moduleTarget.hover();
  await moduleTarget.hover();
  await page.mouse.up();
  await expect(page.locator('.module-title').first()).toHaveValue('Advanced');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('#save-status')).toContainText('Draft saved');
  const courses = await (await page.request.get('/api/v1/admin/courses')).json();
  const course = courses.find(c => c.slug === 'focused-course');
  const saved = await (await page.request.get(`/api/v1/admin/courses/${course.id}`)).json();
  expect(saved.modules.map(m => m.title)).toEqual(['Advanced', 'Introduction']);
  expect(saved.modules[0].lessons.map(l => l.title)).toEqual(['Second lesson', 'First lesson']);
  expect(saved.modules[0].lessons[1].body).toBe('Edited while focused');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Edit one section at a time', { exact: true }).check();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('draft preview switches audiences without publishing and returns to the editor', async ({ page }) => {
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Admin-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('link', { name: 'Administer', exact: true }).click();
  await page.locator('[name=title]').fill('Preview only course');
  await page.locator('[name=slug]').fill('preview-only-course');
  await page.locator('[name=summary]').fill('This is a private draft for preview testing.');
  await page.locator('.module-title').fill('Module');
  await page.locator('.lesson-title').fill('Private lesson');
  await page.locator('.lesson-content').fill('# Draft heading\n\n<script>alert(1)</script>');
  await page.getByRole('button', { name: 'Preview draft', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('.lesson-body h1')).toHaveText('Draft heading');
  await expect(dialog.locator('script')).toHaveCount(0);
  await dialog.getByLabel('Preview as').selectOption('visitor');
  await expect(dialog).toContainText('Enrollment required to view this lesson.');
  await expect(dialog.locator('.lesson-body')).toHaveCount(0);
  await dialog.getByLabel('Preview as').selectOption('learner');
  await expect(dialog.locator('.lesson-body h1')).toHaveText('Draft heading');
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Preview draft', exact: true })).toBeFocused();
  await expect(page.locator('.lesson-content')).toHaveValue('# Draft heading\n\n<script>alert(1)</script>');
  const courses = await (await page.request.get('/api/v1/admin/courses')).json();
  expect(courses.find(c => c.slug === 'preview-only-course').status).toBe('DRAFT');
});

test('incremental autosave retries a network failure without resending unchanged lessons', async ({ page }) => {
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Admin-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('link', { name: 'Administer', exact: true }).click();
  await page.locator('[name=title]').fill('Incremental browser course');
  await page.locator('[name=slug]').fill('incremental-browser-course');
  await page.locator('[name=summary]').fill('Verify incremental saves and local network recovery.');
  await page.locator('.module-title').fill('Module');
  await page.locator('.lesson-title').fill('First');
  await page.locator('.lesson-content').fill('Unchanged first lesson');
  await page.locator('.lesson-editor > .row-controls').getByRole('button', { name: 'Duplicate', exact: true }).click();
  await page.locator('.lesson-title').nth(1).fill('Second');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('#save-status')).toContainText('Draft saved');
  let fail = true;
  const patches = [];
  await page.route('**/api/v1/admin/courses/*', async route => {
    if (route.request().method() !== 'PATCH') return route.continue();
    patches.push(route.request().postDataJSON());
    if (fail) return route.abort();
    return route.continue();
  });
  await page.locator('.lesson-content').nth(1).fill('Only this lesson changed');
  await expect(page.locator('#save-status')).toContainText('Save failed');
  expect(patches[0].changes).toHaveLength(1);
  expect(patches[0].changes[0]).toMatchObject({ unit: 'lesson', module: 0, lesson: 1, value: { body: 'Only this lesson changed' } });
  expect(JSON.stringify(patches[0])).not.toContain('Unchanged first lesson');
  await expect(page.locator('.lesson-content').nth(1)).toHaveValue('Only this lesson changed');
  page.on('dialog', dialog => dialog.accept());
  await page.reload();
  await expect(page.locator('.lesson-content').nth(1)).toHaveValue('Only this lesson changed');
  fail = false;
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('#save-status')).toContainText('Draft saved');
  const courses = await (await page.request.get('/api/v1/admin/courses')).json();
  const course = courses.find(c => c.slug === 'incremental-browser-course');
  const saved = await (await page.request.get(`/api/v1/admin/courses/${course.id}`)).json();
  expect(saved.modules[0].lessons.map(l => l.body)).toEqual(['Unchanged first lesson', 'Only this lesson changed']);
});

test('publication checklist identifies all empty lessons and lets the author correct them', async ({ page }) => {
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Admin-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('link', { name: 'Administer', exact: true }).click();
  await page.locator('[name=title]').fill('Checklist course');
  await page.locator('[name=slug]').fill('checklist-course');
  await page.locator('[name=summary]').fill('Verify all publication blockers appear together.');
  await page.locator('.module-title').fill('Incomplete module');
  await page.locator('.lesson-title').fill('First empty');
  await page.locator('.lesson-editor > .row-controls').getByRole('button', { name: 'Duplicate', exact: true }).click();
  await page.locator('.lesson-title').nth(1).fill('Second empty');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  const card = page.locator('#admin-list .card').filter({ has: page.getByRole('heading', { name: 'Checklist course', exact: true }) });
  await card.getByRole('button', { name: 'Publish', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('First empty');
  await expect(dialog).toContainText('Second empty');
  await expect(dialog.locator('li')).toHaveCount(2);
  await page.keyboard.press('Escape');
  await page.locator('.lesson-content').nth(0).fill('First complete body');
  await page.locator('.lesson-content').nth(1).fill('Second complete body');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('#save-status')).toContainText('Draft saved');
  await card.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(card).toContainText('PUBLISHED');
});
