import { test, expect } from './fixtures';
test('administrator publishes; a learner enrolls and completes an article', async ({ page }) => {
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Admin-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('link', { name: 'Administer', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).first().fill('First steps with Maia');
  await page.getByLabel('Course address').fill('first-steps');
  await page
    .getByLabel('Summary')
    .fill('Learn to create your first project with the Maia platform.');
  await page.getByLabel('Access', { exact: true }).selectOption('ENROLLED_FREE');
  await page.getByLabel('Module title').fill('Introduction');
  await page.getByLabel('Title', { exact: true }).nth(1).fill('Welcome');
  await page
    .getByLabel('Content (text)')
    .fill('Your first project starts here. <script>alert("xss")</script>');
  await page.getByRole('button', { name: 'Add lesson' }).click();
  await page.getByLabel('Title', { exact: true }).nth(2).fill('Build your first project');
  await page.getByLabel('Content (text)').nth(1).fill('Create a small project with Maia.');
  await page.getByRole('button', { name: 'Save draft' }).click();
  const courseCard = page.locator('#admin-list .card').filter({has:page.getByRole('heading',{name:'First steps with Maia',exact:true})});
  await courseCard.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(courseCard.getByText('PUBLISHED', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.goto('/auth/register');
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Learner-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Account created');
  await page.goto('/auth/login');
  await page.getByLabel('Email', { exact: true }).fill('learner@example.com');
  await page.getByLabel('Password', { exact: true }).fill('Learner-test-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My learning' })).toBeVisible();
  await page.goto('/courses/first-steps');
  await page.getByRole('button', { name: 'Enroll for free' }).click();
  await expect(page.getByText('You are enrolled in this course.')).toBeVisible();
  await page.getByRole('link', { name: 'Welcome' }).click();
  await expect(page.locator('.lesson-body')).toContainText('<script>alert("xss")</script>');
  await expect(page.getByRole('navigation', { name: 'Course outline' }).getByRole('link')).toHaveCount(2);
  await expect(page.getByRole('link', { name: 'Next lesson', exact: true })).toBeVisible();
  await page.getByLabel('Language').selectOption('pt-BR');
  await page.locator('#languageSelect').selectOption('pt-BR');
  await expect(page.getByRole('navigation', { name: 'Navegação das aulas' })).toBeVisible();
  await page.locator('#languageSelect').selectOption('es');
  await expect(page.getByRole('link', { name: 'Siguiente lección', exact: true })).toBeVisible();
  await page.locator('#languageSelect').selectOption('en');
  await page.getByRole('button', { name: 'Mark as complete' }).click();
  await expect(page.getByRole('button', { name: 'Lesson completed ✓' })).toBeVisible();
  await page.getByRole('link', { name: 'Next lesson', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Build your first project' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Previous lesson', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'My learning', exact: true }).click();
  await expect(page.getByText('1 of 2 required lessons completed.')).toBeVisible();
  await expect(page.getByText('1 of 2 required lessons completed.')).toBeVisible();
  await page.locator('#languageSelect').selectOption('pt-BR');
  await expect(page.getByRole('link', { name: 'Continuar aprendendo', exact: true })).toBeVisible();
  await page.locator('#languageSelect').selectOption('es');
  await expect(page.getByRole('link', { name: 'Continuar aprendiendo', exact: true })).toBeVisible();
  await page.locator('#languageSelect').selectOption('en');
  await page.getByRole('link', { name: 'Continue learning', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Build your first project' })).toBeVisible();
  await page.goto('/courses');
  await expect(page.getByRole('link', { name: 'First steps with Maia' })).toBeVisible();
  await page.screenshot({ path: 'test-results/catalog.png', fullPage: true });
});
